Fix gh status completion (#730)
This is a (probably crude) attempt to address an issue where using the
`gh status` command with gh completions installed would yield the
following error:

```
> gh status
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[entry #1:1:1]
 1 │ gh status
   ╰────
  help: Usage: gh status {flags} <command> . Use `--help` for more information.
```